In [1]:
#Bu kodda özetle şunları öğrencez;
#Aralıklara bölme
#Aykırı değerleri bulma ve filtreleme
#Satırlardan rastgele örneklem alma
#Dummy değişkenine dönüştürme.

In [2]:
import pandas as pd

In [3]:
#VERİYİ GRUPLARA AYIRMA
#veriyi belli aralıklarda gruplara ayırmak için cut methodu kullanılır.

In [4]:
nt = [30,80,40,90,60,45,95,75,55,100,65,85]

In [5]:
aralik = [20,40,60,80,100]

In [7]:
puan = pd.cut(nt,aralik)
puan

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [9]:
puan.codes #örneğin 30 değeri 0. index değerinin arasında, 80 değeri 2. indexin arasında gibi

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [10]:
puan.categories # kategorilere ayırdı.

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [12]:
pd.value_counts(puan) #kategorilerin sıklıklarını bulmak için yaptık.

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [14]:
#aralıklar normal parantezle başlayıp köşeli parantezle bitiyo
puan = pd.cut(nt,aralik,right = False) #Böyle yaparak bunu halledebiliriz.
puan 

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [15]:
isim = ["dusuk","orta","yuksek","tavan"] #Aralıklara isim verdi.
pd.cut(nt,aralik,labels = isim)

['dusuk', 'yuksek', 'dusuk', 'tavan', 'orta', ..., 'yuksek', 'orta', 'tavan', 'yuksek', 'tavan']
Length: 12
Categories (4, object): ['dusuk' < 'orta' < 'yuksek' < 'tavan']

In [16]:
pd.cut(nt,10) #nt değeri için 10 aralık belirlenmiş oldu.

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [20]:
import numpy as np

veri=np.random.rand(100)
veri

array([0.53809267, 0.75509996, 0.36062102, 0.49292442, 0.78425677,
       0.16669629, 0.45780909, 0.09240712, 0.77175326, 0.21271448,
       0.24190011, 0.60674547, 0.51653719, 0.65554745, 0.25220055,
       0.30679737, 0.61675327, 0.3719215 , 0.79233693, 0.93103486,
       0.07532059, 0.09692106, 0.95607086, 0.66972797, 0.13072142,
       0.73754364, 0.10094351, 0.95901155, 0.64835671, 0.66545962,
       0.44358741, 0.27738355, 0.18987842, 0.75083077, 0.99229592,
       0.1416714 , 0.14326645, 0.70028556, 0.75417981, 0.79411831,
       0.48179735, 0.89728026, 0.41067669, 0.38029888, 0.69987181,
       0.60895273, 0.70373133, 0.65268044, 0.06456806, 0.58149183,
       0.57525327, 0.13512209, 0.25992197, 0.23881709, 0.78640728,
       0.05298471, 0.28721719, 0.89203043, 0.88277365, 0.6026527 ,
       0.28775265, 0.60027277, 0.9947875 , 0.56093456, 0.80530756,
       0.17176644, 0.90038592, 0.77953483, 0.21338246, 0.03456016,
       0.99475346, 0.07721877, 0.23593265, 0.38170907, 0.06578

In [22]:
x = pd.qcut(veri,4) #herbir değerin çeyrek aralığı ekrana gelir.
x

[(0.472, 0.75], (0.75, 0.995], (0.213, 0.472], (0.472, 0.75], (0.75, 0.995], ..., (0.213, 0.472], (0.008480000000000001, 0.213], (0.213, 0.472], (0.008480000000000001, 0.213], (0.008480000000000001, 0.213]]
Length: 100
Categories (4, interval[float64, right]): [(0.008480000000000001, 0.213] < (0.213, 0.472] < (0.472, 0.75] < (0.75, 0.995]]

In [23]:
#Herbir çeyrek aralığa kaç değer düştüğüne bakalım
pd.value_counts(x) 

(0.008480000000000001, 0.213]    25
(0.213, 0.472]                   25
(0.472, 0.75]                    25
(0.75, 0.995]                    25
Name: count, dtype: int64

In [24]:
#AYKIRI DEĞERLERİ FİLTRELEME

In [39]:
veri = pd.DataFrame(np.random.rand(1000,4))

In [40]:
veri.head() # ilk 5 satır 

0         1         2         3
0  0.247036  0.569879  0.070326  0.385715
1  0.995401  0.803184  0.212181  0.920557
2  0.511524  0.704617  0.460536  0.398651
3  0.189339  0.825520  0.937546  0.133673
4  0.555208  0.413450  0.298371  0.080614

In [41]:
veri.describe() #Özet istatistikler karşımıza gelir.

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.515553     0.504564     0.488058     0.510681
std       0.292682     0.290084     0.287241     0.285305
min       0.001816     0.000434     0.001007     0.004233
25%       0.254813     0.254359     0.244583     0.260492
50%       0.523759     0.496174     0.480354     0.514258
75%       0.765770     0.753246     0.740328     0.742807
max       0.998117     0.998680     0.998779     0.999888

In [30]:
sutun = veri[1]

In [52]:
sutun[np.abs(sutun)>0.8] #mutlak değer 0.8 den buyuk değerleri yazar

12     0.998565
20     0.880595
23     0.955510
25     0.911843
28     0.901983
         ...   
942    0.949296
951    0.845586
952    0.824477
958    0.813255
967    0.909562
Name: 1, Length: 180, dtype: float64

In [53]:
np.sign(veri.head()) #Negatif olup olmadığını görmek istersek

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0

In [54]:
#RASTGELE SATIR SEÇME

In [55]:
veri = pd.DataFrame(np.arange(12).reshape(4,3))
veri

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [56]:
sira = np.random.permutation(4) #4 e kadar rastgele bir değer alınmış oldu.
sira 

array([1, 2, 3, 0])

In [57]:
veri.take(sira) #verideki değerlerin sıralamasını değiştirelim

0   1   2
1  3   4   5
2  6   7   8
3  9  10  11
0  0   1   2

In [62]:
#Rastgele satır seçmek için sample methodu kullanılır.
veri.sample( n = 2)

0   1   2
0  0   1   2
3  9  10  11

In [ ]:
#DUMMY DÖNÜŞÜMÜ

In [64]:
veri = pd.DataFrame({"harf":["c","b","a","b","b","a"],"sayi":range(6)})
veri

harf  sayi
0    c     0
1    b     1
2    a     2
3    b     3
4    b     4
5    a     5

In [65]:
pd.get_dummies(veri["harf"])


a      b      c
0  False  False   True
1  False   True  False
2   True  False  False
3  False   True  False
4  False   True  False
5   True  False  False

In [66]:
veri = np.random.randn(10)
veri

array([ 0.13752075, -0.97197043, -0.05483336, -2.53901433, -1.10009112,
       -2.21946692,  0.61182074, -0.41805763, -0.89216289,  1.13102412])

In [67]:
pd.get_dummies(pd.cut(veri,4)) #veri seti 4 aralığa ayrıldı.


(-2.543, -1.622]  (-1.622, -0.704]  (-0.704, 0.214]  (0.214, 1.131]
0             False             False             True           False
1             False              True            False           False
2             False             False             True           False
3              True             False            False           False
4             False              True            False           False
5              True             False            False           False
6             False             False            False            True
7             False             False             True           False
8             False              True            False           False
9             False             False            False            True